@startuml

class Position {
    - int row
    - int column
}

enum Direction {
    SOUTH_EAST
    SOUTH_WEST
    NORTH_EAST
    NORTH_WEST
}

class Board {
- Map<Position, Block> blocks;
- Map<Position, Objective> objectives;
- Map<Position, Laser> lasers;
- int row;
- int column;
-moveBlock(Position from, Position to)
-moveLaser(Position from, Position to)
}

class Objective {
    - Position position;
    + getPosition()
}

class Laser {
    - Direction direction;
    + getDirection(Direction direction)
}

class DisplacementAppiler {
    - Map<Direction, Position> mapDisplacement
    + Position getDisplacement(Direction direction)
    + Position applyDisplacement(Position from, Position delta)
}

interface Block {
    + BlockType getType()
    + void applyEffect()
}



Board o-- Objective
Board o-- Laser
Board o-- Block
Board <-- Position

MirrorBlock ..|> Block
CrystalBlock ..|> Block
EmptyBlock ..|> Block
GlassBlock ..|> Block
MobileOpaqueBlock ..|> Block
FixedOpaqueBlock ..|> Block
NotBlock ..|> Block

Position <-- Laser
Position <-- Objective

Direction <-- Laser

Laser --> Block

MirrorBlock --> DisplacementAppiler
CrystalBlock --> DisplacementAppiler
EmptyBlock --> DisplacementAppiler
GlassBlock --> DisplacementAppiler
MobileOpaqueBlock --> DisplacementAppiler
FixedOpaqueBlock --> DisplacementAppiler
NotBlock --> DisplacementAppiler

@enduml